require_relative 'market/checkout'
require_relative 'market/item'
require_relative 'market/printer'
require_relative 'market/discount'
require_relative 'market/discounter'
require_relative 'market/discounter/appl_discounter'
require_relative 'market/discounter/bogo_discounter'
require_relative 'market/discounter/chmk_discounter'
